### PR TITLE
feat: Added the /verify page UI

### LINKED ISSUE #47: [FEAT] :sparkles: Verification Page
**Description**

This page will be used for verify the token that got from an email after sign up

**Design** 
34F49350-8AB3-4BCC-B1CC-35B5CAF00A0F

**Image**

Get it from folder assets/photos/vector-verify

### Anything 

don’t forget to put label htmlFor attribute and also id in input

Here’s some template to start with

```
//for the main div 
<div className="absolute top-0 left-0 grid h-screen w-screen place-items-center bg-white font-poppins ">
</div>
```

```    
//for the blue box div<div className="relative flex h-auto w-[90vw] max-w-6xl flex-col items-center justify-center gap-4 bg-[#DBE2EF] py-10 md:h-[60vh] md:w-[70vw] md:flex-row md:justify-around"> 
</div>
```

then put the blue box div inside the main div

### PR DESCRIPTION
**Pull request by is-it-ayush**
### Description

I have added the `/verify` page UI with some comment's.

### Checklist:

- [x] This pull request follow our contribution guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (postman and swagger)
- [ ] I have written tests for the code
- [ ] I have updated .env.example file for new .env variables

Closes #47 

### Screenshots
- Screen's Above 1024px
image
- Screen's Below 1024px
image

### CODE REVIEW

**Review by Karol-Ari — CHANGES_REQUESTED** [review]
Check the font.
Right now you have _Poppins sans-serif_, but it should be _Poppins, Light_ and _Poppins Regular_

**Review by KanLSK — APPROVED** [review]

**Comment by is-it-ayush** [comment]
@Karol-Ari Which texts would you like me to make changes on Karol.

**Comment by Karol-Ari** [comment]
If you look at figma texts then you will see

**Comment by is-it-ayush** [comment]
Pull Request Closed Due to Branch Conflict's.

**Pull request closed without merging**
