### PR TITLE
feat: Added hover effect on back button in login and signup page

### LINKED ISSUE #54: [FEAT] :sparkles: Add hover effect on back button in login and signup page
### Description

We can change colour of the back arrow on hover

### Anything else?

Recording 2022-10-07 at 13 28 49

### PR DESCRIPTION
**Pull request by debopriyadey**
### Description
I have wrapped the back button inside a div to which I have applied the CSS. Used tailwind CSS class names for bg color, border and padding. For the hover effect, I have used a custom class name ```back-arrow``` for which the CSS is defined in index.css. I zoomed the arrow and changed the shadow upon hovering.

### Checklist:

- [x ] This pull request follow our contribution guidelines
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation (postman and swagger)
- [ x] I have written tests for the code
- [ x] I have updated .env.example file for new .env variables

### What is current behavior?
#54

Closes #54

### What is new behavior?

[3792ed57-0c2b-44b2-a99a-fcecbfe331de.webm](https://user-images.githubusercontent.com/64556550/194624896-bfc55f2a-e7b2-4706-adfe-c5c0126eef54.webm)

### Breaking Changes?

There are no breaking changes

### Additional information

You can also shift the button left or right using the transform translate.
```
.back-arrow:hover {
  transform: translate(5px, 0px) scale(1.3);
  box-shadow: 4px 4px 15px 1px;
}
```

### CODE REVIEW

**Comment by Karol-Ari** [comment]
I want to change the back button design

**Comment by Karol-Ari** [comment]
back button gif
I want something like this

**Comment by is-it-ayush** [comment]
I like the zoom, Could you change the background color though as @Karol-Ari suggested. Thanks!

**Comment by debopriyadey** [comment]
Yes will do that as well.

**Comment by aayushchugh** [comment]
@debopriyadey just keep color changing effect and Remove zoom

**Review by Karol-Ari — APPROVED** [review]
Amazing job.

**Review by aayushchugh — APPROVED** [review]

**Pull request merged**
