### PR TITLE
fix: replaced favicon with correct logo

### PR DESCRIPTION
**Pull request by Gauravpawar3102**
### Description

 added the favicon of multiemail by replacing the redux favicon, generated a favicon of multiemail from favicon generator and replaced it with the redux favicon

### Checklist:

- [x] This pull request follow our contribution guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (postman and swagger)
- [x] I have written tests for the code
- [x] I have updated .env.example file for new .env variables

### What is current behavior?

186

Closes #(issue_number)

### What is new behavior?

issue is solved now the favicon is changed to multi email logo

### Breaking Changes?

N/A

### Additional information

N/A

### CODE REVIEW

**Comment by aayushchugh** [comment]
@Gauravpawar3102 please share the screenshot of the website with the correct favicon

**Comment by Gauravpawar3102** [comment]
Favicon updated
Favicon

**Review by aayushchugh — APPROVED** [review]
Please rename the PR so that it follows conventional commits, favicon looks good

**Comment by Gauravpawar3102** [comment]
@aayushchugh i have updated the PR title .

**Comment by aayushchugh** [comment]
@all-contributors please add @Gauravpawar3102 for code

**Pull request merged**
